/**
 * 목적: 코드 자산 페이지용 시드를 정의한다.
 * 설명: 코드 카테고리를 DevTools, Docker, Kubernetes로만 유지하고 풍부한 예시 자산을 제공한다.
 * 적용 패턴: 페이지 시드 모듈 패턴
 * 참조: backend/src/db/seed-pages/shared.ts
 */
import { createAsset, iso } from "@/db/seed-pages/shared";
import type { SeedBundle } from "@/db/seed-pages/types";

export const codeAssetsPageSeed: SeedBundle = {
  assetCategories: [
    { id: 1, kind: "code", name: "DevTools", slug: "devtools", sortOrder: 10 },
    { id: 2, kind: "code", name: "Docker", slug: "docker", sortOrder: 20 },
    { id: 3, kind: "code", name: "Kubernetes", slug: "kubernetes", sortOrder: 30 },
  ],
  assets: [
    createAsset({ id: 1, kind: "code", title: "에이전트 툴 계약 검증기", slug: "agent-tool-contract-validator", summary: "에이전트가 호출하는 툴 스펙과 입력·출력 계약을 정적 검증하는 개발 도구", content: "# 에이전트 툴 계약 검증기\n\n에이전트 툴 정의 파일을 읽어 파라미터 누락, 응답 스키마 충돌, 권한 범위 불일치를 검증합니다.\n\n- 구성요소: 툴 manifest 파서, JSON schema 검증기, 변경 diff 리포터\n- 사용 흐름: PR 단계 검증 -> 스키마 diff 출력 -> 호환성 체크\n- 운영 포인트: 툴 추가 시 breaking change를 조기에 감지\n- 확장 전략: MCP 툴 명세와 내부 action spec을 같은 규칙으로 합칩니다.", categoryId: 1, projectId: null, ownerUserId: 1, status: "approved", attachmentName: "agent-tool-contract-validator.zip", attachmentUrl: "https://mock.local/downloads/agent-tool-contract-validator.zip", externalUrl: "https://mock.local/repos/agent-tool-contract-validator", createdAt: iso(1, 11), approvedBy: 1 }),
    createAsset({ id: 2, kind: "code", title: "에이전트 스킬 번들 패키저", slug: "agent-skill-bundle-packager", summary: "프롬프트, 스킬, 정책 파일을 하나의 배포 번들로 묶는 패키징 도구", content: "# 에이전트 스킬 번들 패키저\n\n에이전트 프롬프트, 스킬 문서, tool mapping, 버전 메타데이터를 하나의 번들로 묶어 배포 가능한 산출물로 만듭니다.\n\n- 구성요소: 번들 생성기, 버전 manifest 작성기, 의존 파일 검사기\n- 사용 흐름: 스킬 소스 스캔 -> 번들 생성 -> 릴리스 아카이브 산출\n- 운영 포인트: 배포 시점의 프롬프트/스킬 버전을 고정\n- 확장 전략: Docker 이미지와 Kubernetes ConfigMap 생성기로 연결합니다.", categoryId: 1, projectId: null, ownerUserId: 2, status: "approved", attachmentName: "agent-skill-bundle-packager.tar.gz", attachmentUrl: "https://mock.local/downloads/agent-skill-bundle-packager.tar.gz", externalUrl: "https://mock.local/repos/agent-skill-bundle-packager", createdAt: iso(2, 11), approvedBy: 1 }),
    createAsset({ id: 3, kind: "code", title: "에이전트 대화 Trace 인스펙터", slug: "agent-trace-inspector", summary: "대화 turn, 툴 호출, 비용, 실패 지점을 시각적으로 분석하는 내부 디버깅 도구", content: "# 에이전트 대화 Trace 인스펙터\n\n실행 trace를 타임라인으로 정리해 어떤 turn에서 어떤 툴이 호출됐는지, 어디서 실패했는지 빠르게 파악할 수 있게 합니다.\n\n- 구성요소: trace 수집기, step 타임라인 뷰어, 실패 구간 필터\n- 사용 흐름: 실행 로그 업로드 -> turn/step 탐색 -> 실패 근본 원인 파악\n- 운영 포인트: 장애 재현 없이 운영 로그만으로 원인 분석 가능\n- 확장 전략: 평가 결과, 댓글 알림, 승인 기록과 연결 가능합니다.", categoryId: 1, projectId: null, ownerUserId: 5, status: "approved", attachmentName: "agent-trace-inspector.zip", attachmentUrl: "https://mock.local/downloads/agent-trace-inspector.zip", externalUrl: "https://mock.local/repos/agent-trace-inspector", createdAt: iso(3, 11), approvedBy: 1 }),
    createAsset({ id: 4, kind: "code", title: "에이전트 평가 러너 CLI", slug: "agent-eval-runner-cli", summary: "질문 세트와 기대 응답 기준으로 에이전트 품질을 반복 평가하는 CLI 러너", content: "# 에이전트 평가 러너 CLI\n\n질문 세트, 기대 툴 호출, 응답 점수 기준을 묶어 배치 평가를 돌리고 결과를 비교합니다.\n\n- 구성요소: 평가 시나리오 로더, 실행 러너, 점수 비교 리포터\n- 사용 흐름: 시나리오 선택 -> 배치 실행 -> 점수 리포트 생성\n- 운영 포인트: 프롬프트 수정 전후 품질 변화를 빠르게 비교\n- 확장 전략: Docker 배치 러너와 Kubernetes CronJob으로 이어집니다.", categoryId: 1, projectId: null, ownerUserId: 7, status: "approved", attachmentName: "agent-eval-runner-cli.zip", attachmentUrl: "https://mock.local/downloads/agent-eval-runner-cli.zip", externalUrl: "https://mock.local/repos/agent-eval-runner-cli", createdAt: iso(4, 11), approvedBy: 1 }),
    createAsset({ id: 5, kind: "code", title: "에이전트 게이트웨이 베이스 이미지", slug: "agent-gateway-base-image", summary: "AI 에이전트 API 게이트웨이와 인증 미들웨어를 담는 Docker 베이스 이미지", content: "# 에이전트 게이트웨이 베이스 이미지\n\n에이전트 요청 수신, 인증, 세션 추적, 로그 표준화가 포함된 API 게이트웨이 이미지를 제공합니다.\n\n- 구성요소: FastAPI 런타임, 인증 미들웨어, 요청 로깅, 헬스체크\n- 사용 흐름: 게이트웨이 코드 마운트 -> 이미지 빌드 -> 스테이징 배포\n- 운영 포인트: 공통 보안 헤더와 trace id 전달을 기본 제공\n- 확장 전략: worker 이미지와 compose 스택, Kubernetes 게이트웨이 배포로 연결합니다.", categoryId: 2, projectId: null, ownerUserId: 7, status: "approved", attachmentName: "agent-gateway-base-image.tar", attachmentUrl: "https://mock.local/downloads/agent-gateway-base-image.tar", externalUrl: "https://mock.local/repos/agent-gateway-base-image", createdAt: iso(5, 11), approvedBy: 1 }),
    createAsset({ id: 6, kind: "code", title: "로컬 AI 에이전트 플랫폼 Compose 스택", slug: "local-agent-platform-compose-stack", summary: "게이트웨이, worker, Redis, Postgres, 벡터 저장소를 한 번에 띄우는 로컬 시스템 스택", content: "# 로컬 AI 에이전트 플랫폼 Compose 스택\n\n에이전트 API, 툴 실행 워커, Redis queue, Postgres, 벡터 저장소를 묶어 로컬에서 전체 시스템을 재현합니다.\n\n- 구성요소: gateway, worker, queue, db, vector store, dashboard\n- 사용 흐름: compose up -> seed 적재 -> 샘플 시나리오 실행\n- 운영 포인트: 개발 환경에서 운영형 아키텍처를 그대로 검증 가능\n- 확장 전략: 동일 구성을 Kubernetes manifest로 승격합니다.", categoryId: 2, projectId: null, ownerUserId: 2, status: "approved", attachmentName: "local-agent-platform-compose.yaml", attachmentUrl: "https://mock.local/downloads/local-agent-platform-compose.yaml", externalUrl: "https://mock.local/repos/local-agent-platform-compose-stack", createdAt: iso(6, 11), approvedBy: 1 }),
    createAsset({ id: 7, kind: "code", title: "툴 실행 Sandbox Worker 이미지 팩", slug: "tool-sandbox-worker-image-pack", summary: "코드 실행, 웹 조회, 문서 파싱 등 툴별 sandbox worker 이미지를 묶은 런타임 팩", content: "# 툴 실행 Sandbox Worker 이미지 팩\n\n에이전트가 호출하는 툴을 격리된 worker에서 실행하기 위한 이미지 세트를 제공합니다.\n\n- 구성요소: code runner, web fetcher, document parser, 제한된 네트워크 정책\n- 사용 흐름: 큐에서 작업 수신 -> sandbox 실행 -> 결과 반환\n- 운영 포인트: 툴별 권한과 리소스 한계를 이미지 단위로 분리\n- 확장 전략: Kubernetes worker deployment와 autoscaler 정책으로 연결합니다.", categoryId: 2, projectId: null, ownerUserId: 7, status: "approved", attachmentName: "tool-sandbox-worker-image-pack.tar", attachmentUrl: "https://mock.local/downloads/tool-sandbox-worker-image-pack.tar", externalUrl: "https://mock.local/repos/tool-sandbox-worker-image-pack", createdAt: iso(7, 11), approvedBy: 1 }),
    createAsset({ id: 8, kind: "code", title: "에이전트 배치 평가 리플레이 러너", slug: "agent-batch-eval-replay-runner", summary: "대화 로그를 컨테이너 환경에서 재생하고 점수를 산출하는 배치 평가 러너", content: "# 에이전트 배치 평가 리플레이 러너\n\n실제 대화 로그를 받아 동일한 컨테이너 환경에서 재실행하고 품질 지표를 산출합니다.\n\n- 구성요소: 로그 리플레이 엔진, 점수 집계기, 결과 업로더\n- 사용 흐름: 로그 파일 적재 -> 컨테이너 배치 실행 -> 결과 리포트 저장\n- 운영 포인트: 운영 대화 기반 회귀 테스트를 반복 수행 가능\n- 확장 전략: Kubernetes CronJob 평가 시스템으로 확장합니다.", categoryId: 2, projectId: null, ownerUserId: 6, status: "approved", attachmentName: "agent-batch-eval-replay-runner.zip", attachmentUrl: "https://mock.local/downloads/agent-batch-eval-replay-runner.zip", externalUrl: "https://mock.local/repos/agent-batch-eval-replay-runner", createdAt: iso(8, 11), approvedBy: 1 }),
    createAsset({ id: 9, kind: "code", title: "에이전트 컨트롤 플레인 배포 번들", slug: "agent-control-plane-deployment-bundle", summary: "API gateway, session store, config, ingress를 포함한 에이전트 컨트롤 플레인 배포 번들", content: "# 에이전트 컨트롤 플레인 배포 번들\n\nAI 에이전트 서비스의 외부 진입점과 공통 제어 계층을 Kubernetes에 배포하기 위한 시스템 번들입니다.\n\n- 구성요소: gateway deployment, ingress, config map, session store, auth secret\n- 배포 흐름: namespace 준비 -> config 적용 -> gateway/ingress 배포 -> smoke check\n- 운영 포인트: 인증 헤더, rate limit, trace id 전달을 제어 계층에서 공통 처리\n- 확장 전략: worker stack, queue, vector memory cluster와 분리 배포 가능합니다.", categoryId: 3, projectId: null, ownerUserId: 5, status: "approved", attachmentName: "agent-control-plane-bundle.zip", attachmentUrl: "https://mock.local/downloads/agent-control-plane-bundle.zip", externalUrl: "https://mock.local/repos/agent-control-plane-deployment-bundle", createdAt: iso(9, 11), approvedBy: 1 }),
    createAsset({ id: 10, kind: "code", title: "멀티 에이전트 서빙 시스템 스택", slug: "multi-agent-serving-system-stack", summary: "gateway, planner worker, tool worker, queue, autoscaling을 포함한 멀티 에이전트 서빙 스택", content: "# 멀티 에이전트 서빙 시스템 스택\n\n사용자 요청을 planner, executor, tool worker로 분리해 처리하는 Kubernetes 기반 멀티 에이전트 시스템 패키지입니다.\n\n- 구성요소: gateway, planner deployment, executor deployment, queue, HPA, service mesh rule\n- 배포 흐름: control plane 배포 -> queue 구성 -> worker 배포 -> autoscaling 검증\n- 운영 포인트: worker 분리로 장애 격리와 비용 제어가 쉬움\n- 확장 전략: 평가 러너, replay job, manager approval 이벤트와 연동할 수 있습니다.", categoryId: 3, projectId: null, ownerUserId: 2, status: "approved", attachmentName: "multi-agent-serving-stack.tgz", attachmentUrl: "https://mock.local/downloads/multi-agent-serving-stack.tgz", externalUrl: "https://mock.local/repos/multi-agent-serving-system-stack", createdAt: iso(10, 11), approvedBy: 1 }),
    createAsset({ id: 11, kind: "code", title: "벡터 메모리·큐 인프라 패키지", slug: "vector-memory-queue-infra-pack", summary: "벡터 저장소, Redis queue, PostgreSQL, backup job까지 포함한 상태 저장 인프라 패키지", content: "# 벡터 메모리·큐 인프라 패키지\n\nAI 에이전트 시스템이 의존하는 상태 저장 계층을 Kubernetes에 올리기 위한 인프라 묶음입니다.\n\n- 구성요소: vector DB statefulset, Redis, PostgreSQL, PVC, backup CronJob, network policy\n- 배포 흐름: 스토리지 클래스 확인 -> 상태 저장 계층 배포 -> 연결 검증 -> 백업 스케줄 적용\n- 운영 포인트: 메모리 검색 성능과 작업 큐 안정성을 동시에 보장\n- 확장 전략: 멀티 리전 복제나 읽기 전용 검색 클러스터로 확장 가능합니다.", categoryId: 3, projectId: null, ownerUserId: 5, status: "approved", attachmentName: "vector-memory-queue-infra-pack.tgz", attachmentUrl: "https://mock.local/downloads/vector-memory-queue-infra-pack.tgz", externalUrl: "https://mock.local/repos/vector-memory-queue-infra-pack", createdAt: iso(11, 11), approvedBy: 1 }),
    createAsset({ id: 12, kind: "code", title: "시크릿 순환·Canary 운영 패키지", slug: "secret-rotation-canary-ops-pack", summary: "시크릿 갱신, 점진 배포, 자동 롤백, 장애 복구 훅을 포함한 운영 패키지", content: "# 시크릿 순환·Canary 운영 패키지\n\nAI 에이전트 시스템을 운영 환경에서 안전하게 교체하고 복구하기 위한 Kubernetes 운영 패키지입니다.\n\n- 구성요소: secret rotation job, canary rollout policy, metric gate, rollback hook, restart controller\n- 배포 흐름: 시크릿 갱신 -> canary 배포 -> 지표 확인 -> 자동 승격 또는 롤백\n- 운영 포인트: 모델 키 갱신과 에이전트 버전 배포를 같은 운영 절차로 다룸\n- 확장 전략: 프로젝트 승인 이벤트나 야간 평가 결과와 연계한 자동 배포로 발전시킬 수 있습니다.", categoryId: 3, projectId: null, ownerUserId: 7, status: "approved", attachmentName: "secret-rotation-canary-ops-pack.tgz", attachmentUrl: "https://mock.local/downloads/secret-rotation-canary-ops-pack.tgz", externalUrl: "https://mock.local/repos/secret-rotation-canary-ops-pack", createdAt: iso(12, 11), approvedBy: 1 }),
    createAsset({ id: 13, kind: "code", title: "에이전트 프롬프트 회귀 비교기", slug: "agent-prompt-regression-diff", summary: "프롬프트 변경 전후 응답 차이를 시나리오 기준으로 비교하는 회귀 분석 도구", content: "# 에이전트 프롬프트 회귀 비교기\n\n프롬프트 수정 전후 실행 결과를 비교해 의도치 않은 응답 변화와 툴 호출 차이를 빠르게 찾습니다.\n\n- 구성요소: 시나리오 실행기, 응답 diff 엔진, 점수 비교 리포터\n- 사용 흐름: 기준 프롬프트 실행 -> 변경 프롬프트 실행 -> 결과 diff 검토\n- 운영 포인트: 배포 전 프롬프트 회귀를 빠르게 차단\n- 확장 전략: 배치 평가 러너와 동일 시나리오를 공유합니다.", categoryId: 1, projectId: null, ownerUserId: 5, status: "approved", attachmentName: "agent-prompt-regression-diff.zip", attachmentUrl: "https://mock.local/downloads/agent-prompt-regression-diff.zip", externalUrl: "https://mock.local/repos/agent-prompt-regression-diff", createdAt: iso(13, 11), approvedBy: 1 }),
    createAsset({ id: 14, kind: "code", title: "에이전트 메모리 스냅샷 뷰어", slug: "agent-memory-snapshot-viewer", summary: "세션 메모리와 벡터 검색 컨텍스트를 시각적으로 점검하는 디버깅 뷰어", content: "# 에이전트 메모리 스냅샷 뷰어\n\n대화 세션 메모리, 벡터 검색 결과, 요약 메모를 한 화면에서 확인할 수 있게 정리합니다.\n\n- 구성요소: 세션 메모리 로더, 검색 결과 브라우저, 요약 diff 패널\n- 사용 흐름: 세션 선택 -> 메모리 스냅샷 확인 -> 컨텍스트 누락 분석\n- 운영 포인트: 장문 대화에서 기억 누락 원인 파악에 유리\n- 확장 전략: Trace 인스펙터와 세션 id 기준으로 연결합니다.", categoryId: 1, projectId: null, ownerUserId: 2, status: "approved", attachmentName: "agent-memory-snapshot-viewer.zip", attachmentUrl: "https://mock.local/downloads/agent-memory-snapshot-viewer.zip", externalUrl: "https://mock.local/repos/agent-memory-snapshot-viewer", createdAt: iso(14, 11), approvedBy: 1 }),
    createAsset({ id: 15, kind: "code", title: "에이전트 가드레일 규칙 테스트 키트", slug: "agent-guardrail-rule-test-kit", summary: "금지 응답, 민감정보 노출, 권한 위반 시나리오를 검증하는 규칙 테스트 키트", content: "# 에이전트 가드레일 규칙 테스트 키트\n\n안전 정책과 권한 제한이 제대로 동작하는지 자동으로 검증하는 보안 테스트 묶음입니다.\n\n- 구성요소: 금지 시나리오 세트, 응답 판정기, 정책 누락 리포트\n- 사용 흐름: 테스트 세트 실행 -> 위반 케이스 탐지 -> 규칙 보완\n- 운영 포인트: 릴리스 전 안전 회귀를 빠르게 점검\n- 확장 전략: Kubernetes 배포 전 gate 단계로 붙일 수 있습니다.", categoryId: 1, projectId: null, ownerUserId: 7, status: "approved", attachmentName: "agent-guardrail-rule-test-kit.zip", attachmentUrl: "https://mock.local/downloads/agent-guardrail-rule-test-kit.zip", externalUrl: "https://mock.local/repos/agent-guardrail-rule-test-kit", createdAt: iso(15, 11), approvedBy: 1 }),
    createAsset({ id: 16, kind: "code", title: "툴 호출 시뮬레이터", slug: "tool-call-simulator", summary: "에이전트가 외부 툴을 호출하는 흐름을 로컬에서 시뮬레이션하는 검증 도구", content: "# 툴 호출 시뮬레이터\n\n실제 외부 시스템 없이도 툴 호출 성공, 실패, 지연 상황을 재현해 에이전트 동작을 확인합니다.\n\n- 구성요소: mock tool server, 실패 주입기, 지연 시뮬레이터\n- 사용 흐름: 툴 세트 선택 -> 호출 흐름 재현 -> fallback 동작 확인\n- 운영 포인트: 외부 연동 전 단계 검증에 효율적\n- 확장 전략: sandbox worker 이미지와 함께 사용하면 더 현실적인 테스트가 가능합니다.", categoryId: 1, projectId: null, ownerUserId: 1, status: "approved", attachmentName: "tool-call-simulator.zip", attachmentUrl: "https://mock.local/downloads/tool-call-simulator.zip", externalUrl: "https://mock.local/repos/tool-call-simulator", createdAt: iso(16, 11), approvedBy: 1 }),
    createAsset({ id: 17, kind: "code", title: "에이전트 실행 메트릭 수집기", slug: "agent-execution-metrics-collector", summary: "turn 시간, 툴 호출 수, 실패율을 수집하는 로컬 계측 도구", content: "# 에이전트 실행 메트릭 수집기\n\n에이전트 실행 과정의 응답 시간, 툴 호출 횟수, 오류율을 수집해 품질 지표를 만듭니다.\n\n- 구성요소: 계측 미들웨어, 지표 집계기, 리포트 출력기\n- 사용 흐름: 에이전트 실행 -> 지표 수집 -> 병목 구간 확인\n- 운영 포인트: 느린 에이전트 플로우를 조기에 찾을 수 있음\n- 확장 전략: 장애 대응 대시보드와 같은 지표 체계로 연결 가능합니다.", categoryId: 1, projectId: null, ownerUserId: 6, status: "approved", attachmentName: "agent-execution-metrics-collector.zip", attachmentUrl: "https://mock.local/downloads/agent-execution-metrics-collector.zip", externalUrl: "https://mock.local/repos/agent-execution-metrics-collector", createdAt: iso(17, 11), approvedBy: 1 }),
    createAsset({ id: 18, kind: "code", title: "RAG 메모리 서비스 Docker 스택", slug: "rag-memory-service-docker-stack", summary: "벡터 저장소, 임베딩 워커, 검색 API를 묶어 띄우는 Docker 스택", content: "# RAG 메모리 서비스 Docker 스택\n\n에이전트의 장기 기억 계층을 로컬과 스테이징에서 재현하기 위한 Docker 스택입니다.\n\n- 구성요소: vector DB, embedding worker, retrieval API, admin console\n- 사용 흐름: stack 실행 -> 문서 적재 -> 검색 API 연결 -> 에이전트 테스트\n- 운영 포인트: 메모리 계층만 분리해 빠르게 검증 가능\n- 확장 전략: Kubernetes vector memory 인프라 패키지와 동일 토폴로지로 승격합니다.", categoryId: 2, projectId: null, ownerUserId: 2, status: "approved", attachmentName: "rag-memory-service-docker-stack.yaml", attachmentUrl: "https://mock.local/downloads/rag-memory-service-docker-stack.yaml", externalUrl: "https://mock.local/repos/rag-memory-service-docker-stack", createdAt: iso(18, 11), approvedBy: 1 }),
    createAsset({ id: 19, kind: "code", title: "에이전트 세션 스토어 이미지 세트", slug: "agent-session-store-image-set", summary: "대화 세션, 작업 큐, 캐시 계층을 함께 운영하는 세션 스토어 이미지 세트", content: "# 에이전트 세션 스토어 이미지 세트\n\n대화 세션과 작업 큐를 안정적으로 유지하기 위해 세션 저장소와 캐시 이미지를 묶어 제공합니다.\n\n- 구성요소: session store, Redis cache, queue adapter, backup helper\n- 사용 흐름: 이미지 선택 -> 환경 변수 설정 -> 세션 계층 배포\n- 운영 포인트: 세션 손실 없이 worker를 확장하기 쉬움\n- 확장 전략: Kubernetes stateful 구성과 연결해 운영 이관이 가능합니다.", categoryId: 2, projectId: null, ownerUserId: 7, status: "approved", attachmentName: "agent-session-store-image-set.tar", attachmentUrl: "https://mock.local/downloads/agent-session-store-image-set.tar", externalUrl: "https://mock.local/repos/agent-session-store-image-set", createdAt: iso(19, 11), approvedBy: 1 }),
    createAsset({ id: 20, kind: "code", title: "모델 라우터 컨테이너 팩", slug: "model-router-container-pack", summary: "모델 선택, fallback, 비용 제어 로직을 컨테이너로 분리한 라우터 팩", content: "# 모델 라우터 컨테이너 팩\n\n사용자 요청 특성에 따라 모델을 선택하고 fallback 경로를 제어하는 라우터 컨테이너 묶음입니다.\n\n- 구성요소: router API, fallback policy, usage limiter, logging sidecar\n- 사용 흐름: 요청 라우팅 -> 모델 선택 -> fallback 적용 -> 사용량 집계\n- 운영 포인트: 모델 비용과 품질을 동시에 조절 가능\n- 확장 전략: control plane과 연계해 전사 공통 모델 라우팅 계층으로 확장 가능합니다.", categoryId: 2, projectId: null, ownerUserId: 5, status: "approved", attachmentName: "model-router-container-pack.tar", attachmentUrl: "https://mock.local/downloads/model-router-container-pack.tar", externalUrl: "https://mock.local/repos/model-router-container-pack", createdAt: iso(20, 11), approvedBy: 1 }),
    createAsset({ id: 21, kind: "code", title: "대화 리플레이 배치 이미지", slug: "conversation-replay-batch-image", summary: "실제 대화 로그를 재생해 에이전트 변경 영향을 검증하는 배치 이미지", content: "# 대화 리플레이 배치 이미지\n\n운영에서 수집한 대화 로그를 재실행해 에이전트 품질과 회귀 여부를 검증하는 배치 런타임입니다.\n\n- 구성요소: replay runner, result uploader, score comparator, artifact writer\n- 사용 흐름: 로그 적재 -> 배치 실행 -> 결과 비교 -> 리포트 저장\n- 운영 포인트: 운영 데이터 기반 평가 자동화에 적합\n- 확장 전략: Kubernetes CronJob과 approval gate로 연결 가능합니다.", categoryId: 2, projectId: null, ownerUserId: 6, status: "approved", attachmentName: "conversation-replay-batch-image.tar", attachmentUrl: "https://mock.local/downloads/conversation-replay-batch-image.tar", externalUrl: "https://mock.local/repos/conversation-replay-batch-image", createdAt: iso(21, 11), approvedBy: 1 }),
    createAsset({ id: 22, kind: "code", title: "에이전트 오브저버빌리티 스택 for Docker", slug: "agent-observability-docker-stack", summary: "trace, log, metric을 로컬 컨테이너 환경에서 함께 확인하는 오브저버빌리티 스택", content: "# 에이전트 오브저버빌리티 스택 for Docker\n\n에이전트 실행 로그, trace, 메트릭을 로컬에서 바로 확인할 수 있도록 구성한 관찰용 스택입니다.\n\n- 구성요소: log collector, trace backend, metrics exporter, dashboard\n- 사용 흐름: stack 실행 -> 에이전트 연결 -> 병목 분석 -> 결과 저장\n- 운영 포인트: 로컬에서 운영형 관찰 구조를 미리 검증 가능\n- 확장 전략: Kubernetes 운영 패키지의 관찰 계층으로 이어집니다.", categoryId: 2, projectId: null, ownerUserId: 7, status: "approved", attachmentName: "agent-observability-docker-stack.yaml", attachmentUrl: "https://mock.local/downloads/agent-observability-docker-stack.yaml", externalUrl: "https://mock.local/repos/agent-observability-docker-stack", createdAt: iso(22, 11), approvedBy: 1 }),
    createAsset({ id: 23, kind: "code", title: "에이전트 API Gateway + Worker 클러스터 번들", slug: "agent-api-gateway-worker-cluster-bundle", summary: "API gateway, worker pool, queue, ingress, autoscaler를 하나로 묶은 클러스터 번들", content: "# 에이전트 API Gateway + Worker 클러스터 번들\n\n에이전트 서비스를 Kubernetes에 바로 올릴 수 있도록 gateway와 worker 계층을 하나로 묶은 시스템 번들입니다.\n\n- 구성요소: gateway deployment, worker pool, queue, ingress, HPA, config bundle\n- 배포 흐름: namespace 생성 -> config 적용 -> gateway/worker 동시 배포 -> 오토스케일 검증\n- 운영 포인트: 단일 에이전트에서 멀티 워커 구조로 전환하기 쉬움\n- 확장 전략: 컨트롤 플레인 번들과 분리 배포해 서비스 종류를 늘릴 수 있습니다.", categoryId: 3, projectId: null, ownerUserId: 5, status: "approved", attachmentName: "agent-api-gateway-worker-cluster-bundle.tgz", attachmentUrl: "https://mock.local/downloads/agent-api-gateway-worker-cluster-bundle.tgz", externalUrl: "https://mock.local/repos/agent-api-gateway-worker-cluster-bundle", createdAt: iso(23, 11), approvedBy: 1 }),
    createAsset({ id: 24, kind: "code", title: "에이전트 메모리 클러스터 운영 번들", slug: "agent-memory-cluster-ops-bundle", summary: "벡터 메모리, 세션 캐시, 백업 작업을 포함한 메모리 클러스터 운영 번들", content: "# 에이전트 메모리 클러스터 운영 번들\n\n장기 기억과 세션 기억을 함께 운영하기 위한 Kubernetes 메모리 계층 패키지입니다.\n\n- 구성요소: vector DB cluster, Redis session cache, backup CronJob, restore job, PVC policy\n- 배포 흐름: 저장소 계층 준비 -> 클러스터 배포 -> 백업 잡 연결 -> 복구 검증\n- 운영 포인트: 세션/검색 데이터를 분리 운영해 장애 범위를 줄임\n- 확장 전략: 멀티 리전 메모리 복제와 읽기 전용 검색 노드로 확장 가능합니다.", categoryId: 3, projectId: null, ownerUserId: 7, status: "approved", attachmentName: "agent-memory-cluster-ops-bundle.tgz", attachmentUrl: "https://mock.local/downloads/agent-memory-cluster-ops-bundle.tgz", externalUrl: "https://mock.local/repos/agent-memory-cluster-ops-bundle", createdAt: iso(24, 11), approvedBy: 1 }),
    createAsset({ id: 25, kind: "code", title: "실시간 이벤트 기반 에이전트 파이프라인", slug: "realtime-agent-event-pipeline", summary: "이벤트 수집, planner, executor, callback worker를 묶은 실시간 에이전트 파이프라인", content: "# 실시간 이벤트 기반 에이전트 파이프라인\n\n웹훅, 메시지 큐, planner, executor가 함께 동작하는 실시간 에이전트 시스템 구성을 제공합니다.\n\n- 구성요소: event gateway, queue, planner, executor, callback worker, dead-letter queue\n- 배포 흐름: 이벤트 진입점 배포 -> 큐 구성 -> worker 확장 -> 실패 경로 검증\n- 운영 포인트: 이벤트 폭주 시 단계별 확장과 장애 격리가 가능\n- 확장 전략: 장애 대응 대시보드와 연결해 운영 대응 시간을 줄일 수 있습니다.", categoryId: 3, projectId: null, ownerUserId: 2, status: "approved", attachmentName: "realtime-agent-event-pipeline.tgz", attachmentUrl: "https://mock.local/downloads/realtime-agent-event-pipeline.tgz", externalUrl: "https://mock.local/repos/realtime-agent-event-pipeline", createdAt: iso(25, 11), approvedBy: 1 }),
    createAsset({ id: 26, kind: "code", title: "에이전트 평가·배포 게이트 시스템", slug: "agent-eval-deploy-gate-system", summary: "배치 평가 결과를 기준으로 canary 배포 여부를 결정하는 운영 게이트 시스템", content: "# 에이전트 평가·배포 게이트 시스템\n\n평가 점수와 운영 지표를 기준으로 에이전트 새 버전의 승격 여부를 자동 판단하는 Kubernetes 운영 시스템입니다.\n\n- 구성요소: eval job, metric gate, rollout controller, approval webhook, rollback hook\n- 배포 흐름: 평가 실행 -> 임계치 판정 -> canary 시작 -> 승격 또는 롤백\n- 운영 포인트: 품질 검증과 운영 배포를 같은 절차로 통합 가능\n- 확장 전략: 프로젝트 승인 흐름과 연결해 특정 프로젝트만 선행 적용할 수 있습니다.", categoryId: 3, projectId: null, ownerUserId: 5, status: "approved", attachmentName: "agent-eval-deploy-gate-system.tgz", attachmentUrl: "https://mock.local/downloads/agent-eval-deploy-gate-system.tgz", externalUrl: "https://mock.local/repos/agent-eval-deploy-gate-system", createdAt: iso(26, 11), approvedBy: 1 }),
    createAsset({ id: 27, kind: "code", title: "멀티테넌트 에이전트 운영 패키지", slug: "multi-tenant-agent-ops-pack", summary: "테넌트별 네임스페이스, 리소스 제한, 키 관리까지 포함한 멀티테넌트 운영 패키지", content: "# 멀티테넌트 에이전트 운영 패키지\n\n여러 고객 또는 조직 단위로 에이전트 서비스를 분리 운영하기 위한 Kubernetes 패키지입니다.\n\n- 구성요소: tenant namespace template, resource quota, secret policy, ingress rule, billing label set\n- 배포 흐름: 테넌트 생성 -> 네임스페이스/시크릿 적용 -> 서비스 배포 -> 사용량 태깅 확인\n- 운영 포인트: 고객 분리와 비용 추적을 동시에 만족\n- 확장 전략: 멀티클라우드 비용 최적화 프로젝트와 직접 연결 가능한 구조입니다.", categoryId: 3, projectId: null, ownerUserId: 7, status: "approved", attachmentName: "multi-tenant-agent-ops-pack.tgz", attachmentUrl: "https://mock.local/downloads/multi-tenant-agent-ops-pack.tgz", externalUrl: "https://mock.local/repos/multi-tenant-agent-ops-pack", createdAt: iso(27, 11), approvedBy: 1 }),
  ],
};
